/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JFrame;

/**
 *
 * @author Win10
 */
public class GUIMainMenuPanel extends javax.swing.JPanel
{

    private JFrame _parentFrame;
    public GUIMainMenuPanel(JFrame parentFrame)
    {
        _parentFrame = parentFrame;
        initComponents();
        parentFrame.setContentPane(this);
        parentFrame.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnWeatherNow = new javax.swing.JButton();
        btnForecastWeather = new javax.swing.JButton();
        btnStats = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        btnWeatherNow.setText("Ο Καιρός τώρα");
        btnWeatherNow.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnWeatherNowActionPerformed(evt);
            }
        });

        btnForecastWeather.setText("Πρόβλεψη Καιρού");
        btnForecastWeather.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnForecastWeatherActionPerformed(evt);
            }
        });

        btnStats.setText("Στατιστικά");
        btnStats.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStatsActionPerformed(evt);
            }
        });

        btnExit.setText("Έξοδος");
        btnExit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStats, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(btnWeatherNow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnForecastWeather, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnWeatherNow, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnForecastWeather, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStats, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStatsActionPerformed
    {//GEN-HEADEREND:event_btnStatsActionPerformed
        new GUIForecastWeatherPanel(_parentFrame);
    }//GEN-LAST:event_btnStatsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExitActionPerformed
    {//GEN-HEADEREND:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnWeatherNowActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnWeatherNowActionPerformed
    {//GEN-HEADEREND:event_btnWeatherNowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWeatherNowActionPerformed

    private void btnForecastWeatherActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnForecastWeatherActionPerformed
    {//GEN-HEADEREND:event_btnForecastWeatherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnForecastWeatherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnForecastWeather;
    private javax.swing.JButton btnStats;
    private javax.swing.JButton btnWeatherNow;
    // End of variables declaration//GEN-END:variables
}
